export const RECEIVE_HOME_LIST = 'receive_home_list'
export const RECEIVE_SEARCH_DATA = 'receive_search_data'
export const RECEIVE_CATE_LIST = 'receive_cate_list'
export const RECEIVE_TABS = 'receive_tabs'
export const RECEIVE_RECOMMENT_DATA = 'receive_recomment_data'
export const RECEIVE_AUTO_RECOMMENT_DATA = 'receive_auto_recomment_data'
